### ISSUE TITLE
Enable cgroup

### ISSUE THREAD

**Issue by funnym0nk3y** [PyratLabs/ansible-role-k3s#102]
The server fails to start because of `failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)`. 
This is because on Ubuntu and AFAIK also Raspbian that option is disabled. 

For me there are two questions:
1. Should a fix be integrated to this ansible role or stay seperate and in resposibility of the sysadmin?
2. If this should be integrated here, where do you want me to put it?

**Comment by xanmanning** [comment]
Hi @funnym0nk3y 

In my opinion we probably should not set it in this role and leave it to the system administrator, however we should flag (and fail early) if it is not set.

This would be a "pre-check" in the validation tasks directory to ensure the target machine is configured correctly. I don't have a good test for memory cgroup as yet, so I am open to suggestions.

If there is an ansible fact that identifies whether or not this is enabled, fantastic. If not it'd need to be something portable across platforms. If systemd has a command to identify this feature then I'd say go for that, what I'd want to avoid is something that only works on a Raspberry Pi and breaks it for everyone.

**Comment by funnym0nk3y** [comment]
According to [this](https://github.com/raspberrypi/linux/issues/1950) it is done to reduce memory overhead on possibly low memory Pis. 
In my opinion, we should at least provide a solution as a seperate role or playbook. As it is something k3s needs to work, and is enabled afaik on nearly every Linux distro. What I don't know though is if in other distros that option is set in `cmdline.txt` or if it is enabled at compile time. 

The "official" role for k3s checks if it's being run on a pi via querying the chipset type. But I don't think that's ideal.

**Comment by xanmanning** [comment]
WIP branch does a check: https://github.com/PyratLabs/ansible-role-k3s/runs/2261140520?check_suite_focus=true#step:5:200

If the check fails, then point the operator in the right direction: https://github.com/PyratLabs/ansible-role-k3s/blob/e5c69ec894e4b81843eedf5eb528fd67ff0ae52e/vars/main.yml#L147-L155

**Comment by onedr0p** [comment]
I believe this can be closed.

**Comment by xanmanning** [comment]
Closing as this is now merged in.
