### ISSUE TITLE
Allow configuring a node as server and agent in a cluster

### ISSUE THREAD

**Issue by Yajo** [PyratLabs/ansible-role-k3s#134]
### Summary

Right now this role supports either single-node clusters or clusters where server is in some node(s) and agent is in some other(s).

It would be better if we could decide if a node is server and agent separately.

### Issue Type

- Feature Request

### User Story

_As a_  sysadmin \
_I want to_  be able to define a simple inventory where I don't have to do anything special if a cluster has shared server/agent nodes or not \
_So that_  I can have various clusters of various sizes using the same group definitions.

### Additional Information

I think it would be good to add a new `k3s_agent_node` var that configures an agent in the node if true. This way, if a node has both `k3s_control_node: true` and `k3s_agent_node: true`, it will have both things running.

Note: we can have a main cluster HA cluster with all recommendations implemented, to host most customers, while some specific customer may prefer to just have a 2-node on-prem cluster (yes, not recommended, but still better than just 1-node) where 1 machine is server and both are agents.

**Comment by xanmanning** [comment]
It's implied that if `k3s_control_node: true` that it is an agent node.

You can taint nodes that have `k3s_control_node: true` so that they don't run as agents:

```yaml
k3s_server:
  node-taint:
    - "k3s-controlplane=true:NoExecute"
```

See:

 - https://github.com/PyratLabs/ansible-role-k3s/blob/main/documentation/configuration/node-labels-and-component-args.md

**Comment by Yajo** [comment]
> I suppose a task could be added to append the node-taint...

According to [docs](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#node-labels-and-taints-for-agents):

> If you want to change node labels and taints after node registration you should use kubectl.

So I think the answer depends on what's your design goal with this playbook.

If it is just to bootstrap k3s according to the parameters passed in, I think it should just add that configuration to the node, just as one would do manually.

If it is also to help achieving the desired state for a node, then maybe taints and labels should be a special case where an extra task reapplies them to the node always, after it's booted, to make sure the node really has them.



> You can taint nodes that have `k3s_control_node: true` so that they don't run as agents:

Thanks, regarding this, it seems a simple solution. I just didn't know about it. Maybe just some docs would help fix this issue 😃

**Comment by xanmanning** [comment]
> Thanks, regarding this, it seems a simple solution. I just didn't know about it. Maybe just some docs would help fix this issue :smiley:

I did link to my docs? https://github.com/PyratLabs/ansible-role-k3s/issues/134#issuecomment-881666477

**Comment by Yajo** [comment]
I see... Well, then it's just enough. Thanks!
