### ISSUE TITLE
@xanmanning the changes don't work with `k3s_server` or `k3s_agent`, but when I set `k3s_runtime_config` directly, they work perfectly fine.

### ISSUE THREAD

**Issue by abelfodil** [PyratLabs/ansible-role-k3s#141]
@xanmanning the changes don't work with `k3s_server` or `k3s_agent`, but when I set `k3s_runtime_config` directly, they work perfectly fine.

_Originally posted by @abelfodil in https://github.com/PyratLabs/ansible-role-k3s/issues/139#issuecomment-898910451_

**Comment by xanmanning** [comment]
You shouldn't need to set `k3s_runtime_config` as this is [set by the role](https://github.com/PyratLabs/ansible-role-k3s/blob/main/vars/main.yml#L58-L59) as a [role var](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence).
