### ISSUE TITLE
specify user name and cluster name

### ISSUE THREAD

**Issue by houshym** [PyratLabs/ansible-role-k3s#145]
### Summary

when we provision a bunch of cluster with this ansible role, at the end we have a bunch of config file which all user, context and server is the same and we cannot merge all file into one file. I think adding user name, cluster name, and context as a variable in the role would be usefful

### Issue Type

- Feature Request

### User Story

I want to deploy 100+ clusters. I used this role to automate provisioning but in the end, I should manage 100+ config files separately and I cannot merge them easily. I think it will be useful to add this feature to the role

### Additional Information

```yaml

```

**Comment by xanmanning** [comment]
I don't think this would be in the scope of the role, it sounds more like you have huge technical debt in your Ansible project because all of this could be achieved [with a well structured inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) and maybe to keep some things tidy, [external shared vars files in your project](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html).

The role is only meant to do one thing, build K3S clusters, I can't account for everyone's niche requirements, especially when the requirements I am being asked for is the very purpose for which Ansible exists!

**Comment by houshym** [comment]
maybe I did not get your point, I will not deploy all 100+ cluster all together . I have to install each cluster separately. I will add all cluster to my management server after provisioning. do you mean I can use Ansible in such way that at the end I can merge all config file to one? (my single pane management are k9salpha and rancher)

**Comment by xanmanning** [comment]
You don't need to deploy to all clusters all together, you can specify config in either one inventory file and use the `-l` flag to target specific hosts/groups... alternatively you can specify separate inventories and select inventories with `-i`.

Within each host/group you can specify different hostnames, or variables - so you can name clusters based on host or group vars. Like I say much higher level Ansible administration than this role.

**Comment by ksiggins** [comment]
Is it possible to install a multi-cluster setup reusing the same host(s).  Say I want development and production clusters, all running on the same hosts, I would have my inventory files as defined below.

inventories/development
[k3s_server]
192.168.100.20
192.168.100.21
192.168.100.22

[k3s_agent]
192.168.100.30
192.168.100.31

[k3s_cluster:children]
k3s_server
k3s_agent

[k3s_server:vars]
k3s_control_node=true

[k3s_cluster:vars]
k3s_registration_address=192.168.100.99
k3s_control_token=109isljkfgj0opiwuetr0918u34lj5wjsfjsdlkjflsjs

and inventories/production
[k3s_server]
192.168.100.20
192.168.100.21
192.168.100.22

[k3s_agent]
192.168.100.30
192.168.100.31

[k3s_cluster:children]
k3s_server
k3s_agent

[k3s_server:vars]
k3s_control_node=true

[k3s_cluster:vars]
k3s_registration_address=192.168.100.98
k3s_control_token=2l4kj5lksjdf908723lkjsdlkfjsikl7532ijflkjsd

Same server and agent hosts, but changing the k3s_registration_address and k3s_control_token to be different doesn't seem to work.  If I run the development install first, then follow up with the production install, the production install overwrites the first.  Not sure if this is possible within the this role, but thought I'd ask.
