### ISSUE TITLE
s3 backup

### ISSUE THREAD

**Issue by morriq** [PyratLabs/ansible-role-k3s#146]
Hello, k3s has support for s3 backups: https://rancher.com/docs/k3s/latest/en/backup-restore/#s3-compatible-api-support

I can use it via:

```sh
curl -sfL https://get.k3s.io | sh -s -  --etcd-s3 --etcd-s3-region=eu-central-1 --etcd-s3-bucket=xx --etcd-s3-access-key=XXXX --etcd-s3-secret-key=XXX --etcd-snapshot-schedule-cron='0 */6 * * *'
```

maybe it would be nice to have it in ansible?

**Comment by xanmanning** [comment]
This role already supports it, just add the options to [`k3s_server`](https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration).

What the role doesn't support is to fail when you try to use these options on an earlier version of K3s.
