### ISSUE TITLE
Support Debian Bullseye 

### ISSUE THREAD

**Issue by ieugen** [PyratLabs/ansible-role-k3s#151]
### Summary

Debian 11 was released recently and it would be nice to have it on the list of supported operating systems.

This should track support for it.

Will probably try to setup k3s on it in the next few weeks and report back.

**Comment by Nothing4You** [comment]
note that flannel vxlan is broken on bullseye: https://github.com/k3s-io/k3s/issues/3863

**Comment by covert8** [comment]
debian 11 also switched to nftables as the default, this means that you need to switch to legacy iptables
https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster

**Comment by xanmanning** [comment]
Needs a whole host of checks I think, I did have a look at how to check for iptables but I needed to create a dict to select the right package names.

On my radar.

**Comment by ieugen** [comment]
According to https://andrewmunro.me/posts/2021/08/creating-a-k3s-cluster-on-debian-11-bullseye-step-1-provision/ 

there is `k3s check-config` and https://github.com/k3s-io/k3s/issues/900#issuecomment-551337575 

Solution would be to: set  `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"` . Then, restart .

I am working to see if this works on a raspberry pi.

**Comment by ieugen** [comment]
I failed to make it work on the RP4 running debian 11. 
Will try again when I get some time for this.

**Comment by xanmanning** [comment]
Does it work on Debian Buster with k3s version `>= 1.22.2` ?

**Comment by xanmanning** [comment]
Should be fixed in `v2.12.0`

**Comment by agross** [comment]
I could install on Raspbian Bullseye after installing the `iptables` package. The link provided in the error message is a bit misleading because it refers to Raspbian Buster.

**Comment by onedr0p** [comment]
This looks to be fixed upstream with `v1.22.3+k3s1`, see this issue: https://github.com/k3s-io/k3s/issues/4188
