### ISSUE TITLE
Ability to provide custom parameters for k3s.service

### ISSUE THREAD

**Issue by andrewchen5678** [PyratLabs/ansible-role-k3s#164]
Hi, I have just came across to the need of adding a custom parameter "Environment=GOGC=10" for my k3s.service under a non-production VPS with only 1GB of RAM to reduce memory usage, but there is not a way to add that under templates/k3s.service.j2. It'll be helpful to have a way to do this w/o having to do some manual workaround. Thanks.

**Comment by xanmanning** [comment]
Should be fixed in `v2.12.0`

**Comment by andrewchen5678** [comment]
There is a typo on the word "Environment"

**Comment by onedr0p** [comment]
Looks like this was corrected and should be in 3.0.0+
