### ISSUE TITLE
multiarch k3s_airgap

### ISSUE THREAD

**Issue by tomaszduda23** [PyratLabs/ansible-role-k3s#189]
k3s_airgap does not support multiarch. It is possible to specify only one binary for airgap installation. It should be per arch.

**Comment by crutonjohn** [comment]
i agree, that's probably a great feature to add. I didn't really have that in mind when i was initially developing it.

i'm unsure what the lift will look like to build the logic into the role, however.

unfortunately i'm tied to a few projects at this moment. if i get some free cycles i'll come back to work on it. if you want to try your hand at it i'd be happy to help review and get it merged.

**Comment by crutonjohn** [comment]
In an initial pass, it seems like the user could provide the separate binaries in `./files` something like this:

```
./files/k3s_x86_64
./files/k3s_arm64
...
```

and then have some matching logic to match against ansible's built-in [Magic Variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html), specifically `ansible_architecture`.

**Comment by tomaszduda23** [comment]
Probably it is best to use logic from ensure_downloads.yml. x64 do not have suffix on https://github.com/k3s-io/k3s/releases/tag/v1.23.6%2Bk3s1 so it would be more convenience if names match 1:1
```
./files/k3s
./files/k3s_arm64
```
