### ISSUE TITLE
Write kubeconfig to local desktop...

### ISSUE THREAD

**Issue by projx** [PyratLabs/ansible-role-k3s#191]
Hi

Is there anyway command to download the kubeconfig and merge it with ~/.kube/config?

Thanks

**Comment by xanmanning** [comment]
> Is there anyway command to download the kubeconfig and merge it with ~/.kube/config?

Commands:

- download: `scp user@yourcontrolhost:/etc/rancher/k3s/k3s.yaml /tmp/k3s.yaml`
- merge (using [konfig](https://github.com/corneliusweig/konfig)): `konfig import --save /tmp/k3s.yaml`
