### ISSUE TITLE
Mulitple single node clusters

### ISSUE THREAD

**Issue by posteingang** [PyratLabs/ansible-role-k3s#21]
I try to install multiple single node clusters on all my machines. Unfortunately I can't figure out how I can resolve this with that playbook. Each time I run the playbook it will select multiple master nodes.

**Comment by xanmanning** [comment]
That's a bit of a tough one, at the moment the role either accepts one host and turns it into a standalone server, or accepts multiple hosts and attempts to cluster them.

I'd need to have a bit of a head scratch but I suspect I need to split out the clustering tasks and put a when clause on that block of tasks.

I may need to introduce a new variable called something like `k3s_build_cluster` and set it to true by default.

**Comment by xanmanning** [comment]
Hi @posteingang - Please can you try with release [v1.5.0](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.5.0) ?

It should be available from Ansible Galaxy shortly once Travis-CI has finished running tests.

```text
# ansible-galaxy install -f xanmanning.k3s
```

**Comment by posteingang** [comment]
Hi @xanmanning,
I give the newest version a short test. It looks good so far. Thank you very much for your work.
