### ISSUE TITLE
State per node cannot be changed with group/host variables

### ISSUE THREAD

**Issue by igrybkov** [PyratLabs/ansible-role-k3s#22]
Currently, the playbook uses static import to identify which state should be applied for all nodes and cannot be changed on a per-node basis. This means it's not currently possible to remove a single node from the cluster without affecting all other nodes. And also I'd prefer to keep all vars in host/group vars, but now I should use playbook vars if I want to delete cluster from nodes.

[Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#differences-between-dynamic-and-static)

**Comment by xanmanning** [comment]
I need to have a think on this one...

**Comment by xanmanning** [comment]
Hi @igrybkov - I think I may have fixed this, do you want to give this a go with [v1.5.4](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.5.4)? This will be on Ansible Galaxy shortly.

**Comment by igrybkov** [comment]
Hi @xanmanning,
Can confirm, it's fixed. It has applied two different `state-*` includes for two different hosts based on `host_vars` which is exactly what I was looking for.
Thank you!

**Comment by xanmanning** [comment]
Fantastic, no problem.
