### ISSUE TITLE
Role doesn't let me add to the containerd template k3s uses

### ISSUE THREAD

**Issue by samip5** [PyratLabs/ansible-role-k3s#221]
### Summary

I would like to be able to add custom containerd config to the templated one.

### Issue Type

- Feature Request

### User Story

_As a k3s administator_ \
_I want to apply custom options to containerd_  \
_So that I don't have to handle it outside Ansible_

### Additional Information

Related: https://docs.k3s.io/advanced?#configuring-containerd
Example of what I want to add: https://github.com/kubevirt/containerized-data-importer/blob/f5d0b70b096abd856acff67eb4fc0cab0b474d89/doc/block_cri_ownership_config.md

**Comment by onedr0p** [comment]
I don't think we should implement this since k3s will not support merging containerd configs (it appends only)

https://github.com/k3s-io/k3s/issues/9246
