### ISSUE TITLE
Become should be used for call to k3s-killall.sh

### ISSUE THREAD

**Issue by igrybkov** [PyratLabs/ansible-role-k3s#24]
If the role does not run as root on the playbook level, it fails during uninstallation with

```
TASK [xanmanning.k3s : Run k3s-killall.sh] **********************************************************************************************
fatal: [rpi-node01]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/k3s-killall.sh", "msg": "[Errno 13] Permission denied", "rc": 13}
```

**Comment by igrybkov** [comment]
I've also got permission issue here:
```
name: Ensure NODE_TOKEN is captured from control node`
/var/lib/rancher/k3s/server/node-token
```

**Comment by xanmanning** [comment]
Travis-CI is testing and will push this out to Ansible-Galaxy. I need to add some testing around this as a lot of these bugs are things added that I accepted as PRs. Do you want to check this in [v1.6.1](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.6.1) ?

**Comment by igrybkov** [comment]
Hey @xanmanning,
Thank you for fixing another issue! I've checked and both this one and #25 seems to be working now.
