### ISSUE TITLE
Role fails when k3s_bind_address is set

### ISSUE THREAD

**Issue by igrybkov** [PyratLabs/ansible-role-k3s#25]
Ansible tries to check a port on the localhost and fails as the port is not available.

```
TASK [xanmanning.k3s : Wait for control plane to be ready to accept connections] ********************************************************
fatal: [rpi]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:6443"}
```

A solution could be to add `host: "{{ k3s_bind_address }}"` so it would check correct ip.

**Comment by xanmanning** [comment]
Travis-CI is testing and will push this out to Ansible-Galaxy. I think you're correct. Do you want to check this in [v1.6.1](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.6.1) ?
