### ISSUE TITLE
Ability to install k3s & join as agent node?

### ISSUE THREAD

**Issue by clrxbl** [PyratLabs/ansible-role-k3s#26]
Hi,

First time Ansible user here. I'm trying to make 1 server install k3s and join an existing cluster using specified k3s_control_node_address, k3s_datastore_endpoint & k3s_control_token variables.

However, when doing so, I get the following message:
```
TASK [xanmanning.k3s : Check the conditions when a single controller is defined] 

fatal: [192.168.0.51]: FAILED! => {
    "assertion": "(k3s_controller_count | length == 1) and (k3s_datastore_endpoint is not defined or not k3s_datastore_endpoint) and (k3s_dqlite_datastore is not defined or not k3s_dqlite_datastore)",
    "changed": false,
    "evaluated_to": false,
    "msg": "Control plane configuration is invalid. Please see notes about k3s_control_node and HA in README.md."
}
```

Is it even possible to do what I want? If you need to take a look at my playbooks, they're over at this repository: https://github.com/clrxbl/ansible-ha-k3s

**Comment by clrxbl** [comment]
You're an absolute legend. I'll be sure to check it out later.

**Comment by xanmanning** [comment]
Slight issue with HA control plane that I am working through, it may or may not affect you, I've introduced a regression where a variable isn't set properly. I'm testing a fix now whilst getting coffee to try and re-engage my brain.

**Comment by clrxbl** [comment]
![image](https://user-images.githubusercontent.com/28601081/82832954-f0d8c600-9ebc-11ea-8370-f23e89b37c23.png)

Works beautifully now. I was able to add a new worker through my add-worker.yml file. Thanks for the help & the explanation.

**Comment by xanmanning** [comment]
My pleasure.
