### ISSUE TITLE
Templating error on fresh install in tasks/teardown/drain-and-remove-nodes.yml:3

### ISSUE THREAD

**Issue by alexander-rabenstein** [PyratLabs/ansible-role-k3s#31]
Hi, 

I am trying to setup a fresh cluster with the latest version from galaxy, but I get the following error:

`fatal: [kube_node1]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ k3s_become_for_kubectl | ternary(true, false, k3s_become_for_all) }}): ternary() takes exactly 3 arguments (4 given)"
}
fatal: [kube_node2]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ k3s_become_for_kubectl | ternary(true, false, k3s_become_for_all) }}): ternary() takes exactly 3 arguments (4 given)"
}
fatal: [kube_master]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ k3s_become_for_kubectl | ternary(true, false, k3s_become_for_all) }}): ternary() takes exactly 3 arguments (4 given)"
}`

My site.yml:

`- hosts: all
  roles:
     - { role: xanmanning.k3s}`

I call ansible-playbook:
ansible-playbook site.yml -i inventories/stackit-test/hosts -vvv -become

**Comment by alexander-rabenstein** [comment]
Did not notice i am using an old ansible 2.5 version in my wsl. Upgraded to 2.9, runs well now

**Comment by xanmanning** [comment]
Fair shout, thanks @alexander-rabenstein for providing an update.
