### ISSUE TITLE
Add support for --kube-apiserver-args / audit logging

### ISSUE THREAD

**Issue by clrxbl** [PyratLabs/ansible-role-k3s#32]
^

--kube-apiserver-args seems to be necessary for setting an audit log path.
Adding the ability to pass args through for kube-apiserver like kubelet-args would be great, or an option to easily set an audit path.

**Comment by xanmanning** [comment]
I have added this in [v1.8.0](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.8.0)

It should be available in [Ansible Galaxy](https://galaxy.ansible.com/xanmanning/k3s) in the next hour or so.
