### ISSUE TITLE
--no-deploy option is deprecated

### ISSUE THREAD

**Issue by posteingang** [PyratLabs/ansible-role-k3s#33]
I try to disable the default traefik deployment with the provided option: `k3s_no_traefik: true`, which sets the argument `--no-deploy traefik` in the systemd unit file. This seems to be deprecated. Instead it should be done via the argument `--disable traefik`.

Doc: https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components

Is it possbile to get this in the playbook? Maybe it is better to provide a option to extend the k3s argument list by the user.

Regards,
Martin

**Comment by xanmanning** [comment]
Ah yes, I see it was deprecated 6 months ago

https://github.com/rancher/k3s/commit/0374c4f63d056df01c3e9e8cf4d77a6461169070

**Comment by xanmanning** [comment]
Release [v1.8.1](https://github.com/PyratLabs/ansible-role-k3s/releases/tag/v1.8.1) should be on Ansible Galaxy shortly.
