### ISSUE TITLE
k3s_control_workers / --disable-agent is buggy

### ISSUE THREAD

**Issue by ThomasSteinbach** [PyratLabs/ansible-role-k3s#38]
Settings `k3s_control_workers: false`, which starts k3s with `--disable-agent` is strongly discouraged and leads to a cascade of problems. This variable should be removed.

See:
https://github.com/rancher/k3s/issues/978
https://github.com/rancher/k3s/issues/891

**Comment by xanmanning** [comment]
Thanks @ThomasSteinbach 

I have just opted to remove this option now as per your suggestion.
