### ISSUE TITLE
Add support for embedded etcd for HA masters

### ISSUE THREAD

**Issue by onedr0p** [PyratLabs/ansible-role-k3s#41]
Starting with k3s v1.19 dqlite is being relaced with an embedded etcd

https://github.com/rancher/k3s/releases/tag/v1.19.1-rc1%2Bk3s1

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

This is a breaking change so we'd have to removed dqlite and maybe bump the version of this role to `2.x`

**Comment by xanmanning** [comment]
Thanks @onedr0p 

That will certainly be an interesting breakage. I'm going to think up some checks to try and stop people breaking stuff.

**Comment by onedr0p** [comment]
Unfortunately it seems there is no upgrade path provided by k3s :(

**Comment by onedr0p** [comment]
@xanmanning  1.19.1 is officially out 🥳 

https://github.com/rancher/k3s/releases/tag/v1.19.1%2Bk3s1

I can try to whip up a PR unless you are already on it.

**Comment by onedr0p** [comment]
Actually this might be easier than I thought. I think you just need to rename the variable `k3s_dqlite_datastore` to `k3s_etcd_embedded` or something similar. The steps are identical, its juat if you are using 1.19.1 `--cluster-init` will use etcd instead of dqlite.

**Comment by xanmanning** [comment]
I had seen that, but I'd like to put in something that signifies the change. I'm working on it currently, but basically I want to remove the dqlite option from the README but keep it in code and complain if anyone uses it. This means that existing users of dqlite who update the role will be made aware of this breaking change and will be prevented from upgrading to v1.19.

**Comment by onedr0p** [comment]
That sounds like an great plan. I am running thru a fresh install now with 1.10.0 of you role. I'll see if I can break anything :)

**Comment by onedr0p** [comment]
Looks almost good, but maybe we have to bump this timeout? @xanmanning 

```
TASK [xanmanning.k3s : Ensure secondary masters are started] *****************************************************************************
Thursday 17 September 2020  17:17:52 -0400 (0:00:00.528)       0:00:29.159 ****
skipping: [k8s-master-a]
FAILED - RETRYING: Ensure secondary masters are started (3 retries left).
FAILED - RETRYING: Ensure secondary masters are started (2 retries left).
FAILED - RETRYING: Ensure secondary masters are started (1 retries left).
fatal: [k8s-master-b]: FAILED! => {"attempts": 3, "changed": false, "msg": "Could not find the requested service k3s: host"}
changed: [k8s-master-c]
```

**Comment by onedr0p** [comment]
I can confirm bumping the delay to 5 solves the issue:

```
TASK [xanmanning.k3s : Ensure secondary masters are started] *****************************************************************************
Thursday 17 September 2020  17:46:20 -0400 (0:00:00.508)       0:00:29.541 ****
skipping: [k8s-master-a]
FAILED - RETRYING: Ensure secondary masters are started (3 retries left).
ok: [k8s-master-c]
changed: [k8s-master-b]
```

**Comment by xanmanning** [comment]
Thanks @onedr0p - I've pushed that up now, v1.11.1 will be available from Galaxy in the next hour.

**Comment by onedr0p** [comment]
thank you! I'll go ahead and close this issue.

I noticed kubectl doesn't work after rebooting all the hosts but this is upstream issue.
