### ISSUE TITLE
k3s_no_metrics_server doesn't work

### ISSUE THREAD

**Issue by gloomytrousers** [PyratLabs/ansible-role-k3s#56]
After many problems with getting metrics-server to work out of the box with k3s, I decided to disable it. I ran `sudo /usr/local/bin/k3s-uninstall.sh` on all my nodes, set `k3s_no_metrics_server: true`, and re-ran the playbook.

However, all these files got created anyway, and the metrics-server is running on my clean install.
```
pi@pi1:~ $ sudo ls -l /var/lib/rancher/k3s/server/manifests/metrics-server/
total 28
-rw------- 1 root root 393 Oct 18 12:42 aggregated-metrics-reader.yaml
-rw------- 1 root root 308 Oct 18 12:42 auth-delegator.yaml
-rw------- 1 root root 329 Oct 18 12:42 auth-reader.yaml
-rw------- 1 root root 298 Oct 18 12:42 metrics-apiservice.yaml
-rw------- 1 root root 955 Oct 18 12:42 metrics-server-deployment.yaml
-rw------- 1 root root 291 Oct 18 12:42 metrics-server-service.yaml
-rw------- 1 root root 517 Oct 18 12:42 resource-reader.yaml
```

This is v1.14.1 of the role.

**Comment by xanmanning** [comment]
Thanks for spotting this @gloomytrousers - I have found the issue which is a problem with the logic in the j2 template for the systemd unit file.

Fix should be available in [v1.14.2](https://github.com/PyratLabs/ansible-role-k3s/tree/v1.14.2) which should be available on [ansible-galaxy](https://galaxy.ansible.com/xanmanning/k3s) in the next hour.

**Comment by gloomytrousers** [comment]
Thanks for the quick response @xanmanning , I'll test this tomorrow.

**Comment by gloomytrousers** [comment]
Confirmed, all good here now - metrics-server not deployed.
