### ISSUE TITLE
Step "Ensure NODE_TOKEN is captured from control node" fails when k3s_node_data_dir is set

### ISSUE THREAD

**Issue by gloomytrousers** [PyratLabs/ansible-role-k3s#57]
I have some external (GlusterFS) storage on my RPi cluster, and want to use it for my node data to keep IO off the SD cards. I set:
```
k3s_node_data_dir: /mnt/vol1/data/k3s-node-data/{{ inventory_hostname_short }}
```

However, the play fails with:
```
TASK [xanmanning.k3s : Ensure NODE_TOKEN is captured from control node] ***********************************************************************
fatal: [pi3.example.com -> pi1.example.com]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}
fatal: [pi1.example.com -> pi1.example.com]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}
fatal: [pi2.example.com -> pi1.example.com]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/rancher/k3s/server/node-token"}
```

Presumably the path used here should look at `k3s_node_data_dir` rather than hard-coding `/var/lib/rancher/k3s`

I've hacked around it for now by creating a symlink (`/var/lib/rancher/k3s/server/node-token -> /mnt/vol1/data/k3s-node-data/{{ inventory_hostname_short }}/server/node-token`) prior to running the playbook (alas it seems my GlusterFS volume does not perform well enough for etcd, so the cluster will not start cleanly, but that's a separate issue).

Apart from this, some items are still being written to /var/lib/rancher/k3s:
```
/var/lib/rancher/k3s/agent:
total 4
drwxr-xr-x 2 root root 4096 Oct 19 11:21 etc

/var/lib/rancher/k3s/data:
total 8
lrwxrwxrwx 1 root root   90 Oct 19 11:35 current -> /var/lib/rancher/k3s/data/fbfb39c320a19fb3272085217e4af756f65827d57ae252b6b1e4277fa6d47b45
drwxr-xr-x 4 root root 4096 Oct 19 11:35 fbfb39c320a19fb3272085217e4af756f65827d57ae252b6b1e4277fa6d47b45
```

I also note that the k3s-uninstall.sh script doesn't remove the `k3s_node_data_dir` if it differs from the default; only `/var/lib/rancher/k3s` is removed.

This is using v0.14.2 of the role.

**Comment by xanmanning** [comment]
I've popped in a branch that I _think_ fixes this issue, but I am not 100% sure. 

If you're able to, could you clone this repo and checkout the branch `bugfix-k3s_node_data_dir` ?
