### ISSUE TITLE
v2 is missing

### ISSUE THREAD

**Issue by Marx2** [PyratLabs/ansible-role-k3s#64]
As Ansible is moving towards collections, I've found out in readme, that v1 version of this role is limited to older Ansible 2.9. For newest 2.10 it's suggested to use v2 role (should it be collection?). However, there's no v2 in Ansible Galaxy. The only v2 I can find is a branch here. How should i use this role with Ansible 2.10?

**Comment by xanmanning** [comment]
Hi @Marx2 

Apologies, I am working towards v2 and part of this process requires an update to the v1 README.md. I prematurely committed some changes to the README.md that I was not meant to publish until v2 was released, I will be overlapping support for v1 and v2 for a few months.

More information on migrating from v1 to v2 will be documented as part of the release. Watch this space.

**Comment by xanmanning** [comment]
Hi @Marx2 

[v2.0.0 has been released](https://github.com/PyratLabs/ansible-role-k3s/releases/tag/v2.0.0) :slightly_smiling_face:
