### ISSUE TITLE
include full config file including defaults

### ISSUE THREAD

**Issue by martinfriedrich** [PyratLabs/ansible-role-k3s#66]
### Summary

The recent change to config file based configuration removed the default values from this role
Would be great if we could include all variables including their defaults in the role

**Comment by xanmanning** [comment]
Hi @martinfriedrich 

I'd be more in favour of providing documentation for example configuration. My reasoning behind this is that I'd like to keep the K3s docs as the main source of truth; trying to keep on top of new and changing configuration options has made this role difficult to maintain in the past.

For the v1 role, for every configuration option that was supported I kept (or at least attempted to keep) the `defaults/main.yml` in line with the below documents:

https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
