### ISSUE TITLE
Support custom runtime arguments to the k3s service

### ISSUE THREAD

**Issue by gtie** [PyratLabs/ansible-role-k3s#81]
### Summary

The role currently does not allow custom arguments to be passed to the k3s systemd service.

### Issue Type

- Feature Request

### User Story

_As a_ cluster admin \
_I want to_ be able to pass custom runtime arguments to k3s
_So that_ I can customize its behavior

### Additional Information

Per https://rancher.com/docs/k3s/latest/en/networking/, the cluster can be customized by passing parameters such as `--disable coredns`, `--disable traefik`, etc

**Comment by xanmanning** [comment]
Hi @gtie 

This is all controlled by [k3s config file](https://rancher.com/docs/k3s/latest/en/installation/install-options/#configuration-file), have you tried...

```yaml
k3s_server:
  disable:
    - coredns
    - traefik
```

See: https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

**Comment by xanmanning** [comment]
Closing as this is already achievable in config file as per [README.md](https://github.com/PyratLabs/ansible-role-k3s/tree/main/README.md).

Feature appeared very early in [v1 release](https://github.com/PyratLabs/ansible-role-k3s/tree/v1_release/README.md).

**Comment by gtie** [comment]
Thanks for the pointer. I passing the `k3s_server` var to the role is indeed working.
