### ISSUE TITLE
Uninstall fails to remove binaries with k3s_install_hard_links

### ISSUE THREAD

**Issue by Diaoul** [PyratLabs/ansible-role-k3s#88]
Running uninstalled state after installing with `k3s_install_hard_links: true` fails on *[Fail if k3s binaries have not been removed](https://github.com/PyratLabs/ansible-role-k3s/blob/main/tasks/validate/state/uninstalled.yml#L26-L35)* with all binaries except `k3s`.

Maybe [this](https://github.com/PyratLabs/ansible-role-k3s/blob/main/templates/k3s-uninstall.sh.j2#L28-L32) is related?

**Comment by xanmanning** [comment]
Ah yes, I've updated the uninstall script from upstream and they don't handle hard links in the uninstall. I'll have a think how best to either work with the script or alter it.

**Comment by Diaoul** [comment]
Or make a second pass to delete binaries in case of hard_link option is enabled?

**Comment by xanmanning** [comment]
Indeed

**Comment by xanmanning** [comment]
Hi @Diaoul - Should now be fixed in v2.5.1 :slightly_smiling_face:

**Comment by Diaoul** [comment]
🎉
