### ISSUE TITLE
Missing become for k3s_state=restarted (possibly others)

### ISSUE THREAD

**Issue by Diaoul** [PyratLabs/ansible-role-k3s#89]
Not sure if this is a bug or the expected behavior but there is no become in start/stop it seems. I would've expected one since I use `k3s_become_for_all`. Maybe add `k3s_become_for_control` for start/stop/restart?

**Comment by xanmanning** [comment]
Hi @Diaoul - Should now be fixed in v2.5.1 :slightly_smiling_face:

**Comment by Diaoul** [comment]
Awesome ! Thanks 👍
