### ISSUE TITLE
2.5.0+ should work on ansible 2.19.17 but refuses

### ISSUE THREAD

**Issue by gloomytrousers** [PyratLabs/ansible-role-k3s#91]
### Summary

I'm on Fedora 33 and have just updated the role from 2.2.0 to 2.5.2. As per #83 and #87, I think I should be able to run my playbook on version ansible-2.9.17-2.fc33.noarch (from the Fedora updates-testing repo) but I get an error "Ansible v2.9.17 is not supported by this role. Please install >= v2.10.4".

Am I missing something? I downgraded back to 2.2.0 and my playbook works. I can't work out what I've done wrong here. 

### Issue Type

- Bug Report

```text
[russ@gigalith infrastructure-ansible]$ ansible --version
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/russ/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Jan 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

### Steps to Reproduce

* Up-to-date Fedora 33 with Ansible 2.9.17 installed from updates-testing repo.

* Install latest version of role with `ansible-galaxy role install xanmanning.k3s --force` (2.5.2 at time of writing)

* Run playbook which uses the xanmanning.k3s role.

### Expected Result

Playbook runs.

### Actual Result

Playbook fails:

```text
TASK [xanmanning.k3s : Check that Ansible v2.9.17 is supported by this role] ******************************************************************
fatal: [host.example.com]: FAILED! => {
    "assertion": "ansible_version.string is version_compare(k3s_ansible_min_version, '>=')",
    "changed": false,
    "evaluated_to": false,
    "msg": "Ansible v2.9.17 is not supported by this role. Please install >= v2.10.4"
}

NO MORE HOSTS LEFT ****************************************************************************************************************************
```

**Comment by xanmanning** [comment]
Huge brain fart. Please try v2.5.3

**Comment by gloomytrousers** [comment]
That's fixed it. Many thanks for the speedy response!
