### ISSUE TITLE
nuke playbook

### ISSUE THREAD

**Issue by brunnels** [PyratLabs/ansible-role-k3s#93]
Can you please add a nuke playbook to put all hosts back to original state?  

I found the /usr/local/bin/k3s-uninstall.sh but this takes a while to do manually if you have a bunch of hosts.

I also tried `ansible-playbook -i inventory.yml cluster.yml --become -e 'k3s_state=uninstalled'` but this doesn't do everything that the uninstall script does.

**Comment by xanmanning** [comment]
Not sure I quite understand how the Ansible instruction differs from you running the manual instruction.

`ansible-playbook -i inventory.yml cluster.yml --become -e 'k3s_state=uninstalled'` runs `k3s-uninstall.sh` for you.

**Comment by brunnels** [comment]
Strange.  When I ssh into the hosts I'm still able to run ```/usr/local/bin/k3s-uninstall.sh``` after setting the host to uninstalled.  Trying it again now.

**Comment by brunnels** [comment]
Now I'm getting an error.
`ansible-playbook -i inventory.yml ha_cluster.yml --become -e 'k3s_state=uninstalled' -l "k8s-node-01"`

|  |
|--------------------------------|
|TASK [xanmanning.k3s : Ensure uninstalled nodes are drained] ***********************************************************************************************************************************************
failed: [k8s-node-01 -> 10.0.0.11] (item=k8s-node-01) => {"ansible_loop_var": "item", "changed": true, "cmd": ["/usr/local/bin/kubectl", "drain", "k8s-node-01", "--ignore-daemonsets", "--delete-local-data"], "delta": "0:00:01.597192", "end": "2021-02-28 11:46:12.334242", "item": "k8s-node-01", "msg": "non-zero return code", "rc": 1, "start": "2021-02-28 11:46:10.737050", "stderr": "Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.\nerror: unable to drain node \"k8s-node-01\", aborting command...\n\nThere are pending nodes to be drained:\n k8s-node-01\nerror: cannot delete Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): default/dnsutils", "stderr_lines": ["Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.", "error: unable to drain node \"k8s-node-01\", aborting command...", "", "There are pending nodes to be drained:", " k8s-node-01", "error: cannot delete Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): default/dnsutils"], "stdout": "node/k8s-node-01 cordoned", "stdout_lines": ["node/k8s-node-01 cordoned"]}aged by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): default/dnsutils"], "stdout": "node/k8s-node-01 cordoned", "stdout_lines": ["node/k8s-node-01 cordoned"]}|

**Comment by xanmanning** [comment]
I think that's something to do with pod "default/dnsutils" not being managed by a `ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet`. By chance, what is managing the deployment?

AFAIK, there isn't anything wrong with the process of draining, I have tested this out now with the latest release:

https://asciinema.org/a/VHs4aiB85bLaajJYkc4TkcOP1

I am about to put in a few changes for some small tidying up of the code and some additional pre-checks from another issue - I will add the `--force` flag to the drain command which should allow this to move on.

**Comment by brunnels** [comment]
Looks good now.  uninstalled does a full remove.
